#!#
# Copyright (c) 2025 Hangzhou Guanwaii Technology Co., Ltd.
#
# This source code is licensed under the MIT License,
# which is located in the LICENSE file in the source tree's root directory.
#
# File: .coderabbit.yaml
# Author: mingcheng (mingcheng@apache.org)
# File Created: 2025-09-21 17:35:09
#
# Modified By: mingcheng (mingcheng@apache.org)
# Last Modified: 2025-09-21 18:51:09
##

language: en-US

labels:
  - "code-rabbit"

reviews:
  disable_cache: true
  high_level_summary: true
  path_filters:
    - "**/src/**"
    - "!target/**"
    - "!assets/**"
    - "!templates/**"
    - "!*.lock"
  auto_review:
    enabled: true
    drafts: false
  tools:
    clippy:
      enabled: true
